# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gnt < Formula
  desc "Easily create your Go projects in the terminal."
  homepage "https://github.com/lnxwizard/gnt"
  version "0.8.0-beta"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lnxwizard/gnt/releases/download/0.8.0-beta/gnt_0.8.0-beta_darwin_amd64.zip"
      sha256 "f28af3888b60bfc38d5021673de49e730d5115a0a2f18670387c1a39fae2a2a2"

      def install
        bin.install "bin/gnt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lnxwizard/gnt/releases/download/0.8.0-beta/gnt_0.8.0-beta_darwin_arm64.zip"
      sha256 "873c6bf1aedf44a254e818522313405f23af9350db8a92f48216312bb8039c9c"

      def install
        bin.install "bin/gnt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lnxwizard/gnt/releases/download/0.8.0-beta/gnt_0.8.0-beta_linux_amd64.tar.gz"
      sha256 "dee49185ceb327eae97b25dc9c63983b60f827ae5d10f0b10c97d1d1f2ad3a36"

      def install
        bin.install "bin/gnt"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/lnxwizard/gnt/releases/download/0.8.0-beta/gnt_0.8.0-beta_linux_armv6.tar.gz"
      sha256 "31f8a69f9a7f30dc28bbb5be742fe46a941fb27be9e316fbd610a601a44ce542"

      def install
        bin.install "bin/gnt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lnxwizard/gnt/releases/download/0.8.0-beta/gnt_0.8.0-beta_linux_arm64.tar.gz"
      sha256 "7772f704d5ed46b6214aeac73cb3c5ffdd9195aba73ce62a94297c957253b6ec"

      def install
        bin.install "bin/gnt"
      end
    end
  end
end
